title: Ugne Sakenyte
logo: images/portrait.jpeg 
description: > 
  <br>
  MSc in Statistics graduate at the University of Geneva, former credit ratings analyst of DACH banking sector at Moodys Investors Service.
  <br><br>
  <a href="https://www.linkedin.com/in/ugne-sakenyte/">View my LinkedIn Profile</a> 

#show_downloads: true
theme: jekyll-theme-minimal
