title: Ugne Sakenyte
logo: images/portrait.jpeg 
description: > 
  <br>
  MSc in Statistics | University of Geneva
  <br><br>
  <a href="https://www.linkedin.com/in/ugne-sakenyte/">View my LinkedIn Profile</a> 

#show_downloads: true
theme: jekyll-theme-minimal
