title: Ugne Sakenyte
logo: images/portrait.jpeg 
description: 
  <p align="center">
  <a href="docs/CV_Ugne_Sakenyte.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/ugne-sakenyte/">LinkedIn</a> |
  <a href="https://github.com/ugne-sak">GitHub</a>
  </p>

  <p align="justify">
  MSc in Statistics graduate at the University of Geneva, former credit ratings analyst of Swiss, German and Austrian banking sector at Moody's Investors Service.
  <br><br>

#show_downloads: true
theme: jekyll-theme-minimal
